[assign]
warn_non_default_branch = true
contributing_url = "https://github.com/teloxide/teloxide/blob/master/CONTRIBUTING.md"
users_on_vacation = ["@syrtcevvi"]

[assign.adhoc_groups]
# This is a special group that will be used if none of the `owners` entries matches.
fallback = ["@hirrolot", "@shdwchn10", "@LasterAlex"]

[assign.owners]
"crates/teloxide-ng" = ["@hirrolot", "@LasterAlex", "@shdwchn10"]
"crates/teloxide-core-ng" = ["@LasterAlex", "@shdwchn10"]
"crates/teloxide-macros-ng" = ["@hirrolot", "@LasterAlex"]
".devcontainer" = ["@shdwchn10"]


[autolabel."S-waiting-on-review"]
new_pr = true

#[autolabel."new-issue"]
#new_issue = true

[autolabel."C-core"]
trigger_files = ["crates/teloxide-core-ng/"]

[autolabel."C-main"]
trigger_files = ["crates/teloxide-ng/"]

[autolabel."C-macros"]
trigger_files = ["crates/teloxide-macros-ng/"]

[autolabel."A-dialogue"]
trigger_files = ["crates/teloxide-ng/src/dispatching/dialogue/"]

[autolabel."A-dispatching"]
trigger_files = ["crates/teloxide-ng/src/dispatching/"]

[autolabel."A-macros"]
trigger_files = ["crates/teloxide-macros-ng/"]

[autolabel."A-requester"]
trigger_files = ["crates/teloxide-core-ng/src/requests/requester.rs", "crates/teloxide-core-ng/src/requests/requester_ext.rs"]

[autolabel."A-requests"]
trigger_files = ["crates/teloxide-core-ng/src/requests/", "crates/teloxide-core-ng/src/payloads/"]

[autolabel."A-tba-errors"]
trigger_files = ["crates/teloxide-core-ng/src/errors.rs"]

[autolabel."A-tba-types"]
trigger_files = ["crates/teloxide-core-ng/src/types"]

[autolabel."A-update-listeners"]
trigger_files = ["crates/teloxide-ng/src/update_listeners"]

[relabel]
allow-unauthenticated = [
    "S-*", # Status
    "C-*", # Crate
    "breaking change",
    "bug",
    "documentation",
    "duplicate",
    "feature-request",
    "FIXME",
    "frozen",
    "proposal",
    "question",
    "tba-update",
    "Unknown API error",
    "WIP",
]


# https://forge.rust-lang.org/triagebot/github-releases.html?


[review-submitted]
# This label is added when a review is submitted.
reviewed_label = "S-waiting-on-author"
# These labels are removed when a review is submitted.
review_labels = ["S-waiting-on-review"]

[review-requested]
# Those labels are removed when PR author requests a review from an assignee
remove_labels = ["S-waiting-on-author"]
# Those labels are added when PR author requests a review from an assignee
add_labels = ["S-waiting-on-review"]

[shortcut]


